create table audit_logs (
 id bigint generated by default as identity primary key,
 created_at timestamp with time zone not null,
 actor_type varchar(12) not null check(actor_type in ('USER','ANONYMOUS')),
 actor_id uuid,
 action varchar(60) not null,
 resource_type varchar(30) not null,
 resource_id varchar(100),
 outcome varchar(12) not null check(outcome in ('SUCCESS','DENIED','FAILURE')),
 http_status integer not null check(http_status between 100 and 599),
 request_id varchar(64),
 duration_ms bigint not null
);
create index audit_created on audit_logs(created_at,id);
create index audit_actor_created on audit_logs(actor_id,created_at);
create index audit_action_created on audit_logs(action,created_at);
